"""
NetInsight
scanner.py

This module is responsible for scanning nearby Wi-Fi networks.
Currently, only Windows is supported.
"""

import platform
import subprocess
from dataclasses import dataclass
from typing import List


@dataclass
class WiFiNetwork:
    """
    Represents a detected Wi-Fi network.
    """

    ssid: str
    signal: int
    channel: int


class ScannerError(Exception):
    """Raised when the Wi-Fi scan fails."""
    pass


def scan_networks() -> List[WiFiNetwork]:
    """
    Scan nearby Wi-Fi networks.

    Returns:
        List[WiFiNetwork]: A list of detected Wi-Fi networks.

    Raises:
        ScannerError: If the scan cannot be completed.
    """

    if platform.system() != "Windows":
        raise ScannerError("Only Windows is currently supported.")

    try:
        result = subprocess.run(
            ["netsh", "wlan", "show", "networks", "mode=bssid"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="ignore"
        )

    except Exception as error:
        raise ScannerError(f"Unable to execute netsh: {error}")

    return parse_scan(result.stdout)


def parse_scan(output: str) -> List[WiFiNetwork]:
    """
    Parse the output generated by netsh.

    This is a temporary parser and will be improved in future versions.
    """

    networks: List[WiFiNetwork] = []

    current_ssid = ""
    current_signal = 0
    current_channel = 0

    for line in output.splitlines():

        line = line.strip()

        if line.startswith("SSID"):
            current_ssid = line.split(":", 1)[1].strip()

        elif line.startswith("Signal") or line.startswith("Señal"):
            value = line.split(":", 1)[1].replace("%", "").strip()
            current_signal = int(value)

        elif line.startswith("Channel") or line.startswith("Canal"):
            value = line.split(":", 1)[1].strip()

            try:
                current_channel = int(value)
            except ValueError:
                current_channel = 0

            networks.append(
                WiFiNetwork(
                    ssid=current_ssid,
                    signal=current_signal,
                    channel=current_channel
                )
            )

    return networks
